### ISSUE TITLE
Overriding of bean RabbitListenerAnnotationBeanPostProcessor is broken

### ISSUE THREAD

**Issue by vavrfam** [spring-projects/spring-amqp#984]
## Bug report

We are upgrading our application from  `Springboot 2.1.3` to  `Springboot 2.1.4` release, which uses `spring-amqp 2.1.5.RELEASE`

Found that with new release , overriding of bean  `RabbitListenerAnnotationBeanPostProcessor` does not work.
We do have the property `spring.main.allow-bean-definition-overriding=true` that enables bean overriding.

Following is the sample code. `postProcessAfterInitialization` never gets called.

```
@Configuration
@Import(RabbitAutoConfiguration.class)
public class DemoConfig {


    @Bean(name = RabbitListenerConfigUtils.RABBIT_LISTENER_ANNOTATION_PROCESSOR_BEAN_NAME)
    @Primary
    public RabbitListenerAnnotationBeanPostProcessor rabbitListenerAnnotationProcessor() {
        return new CustomRabbitAnnotationListener();
    }

    public class CustomRabbitAnnotationListener extends RabbitListenerAnnotationBeanPostProcessor {

        @Override
        public Object postProcessAfterInitialization(final Object bean, final String beanName) {
            super.postProcessAfterInitialization(bean, beanName);
            System.out.println("Processing Bean: " + bean.getClass());
            return bean;
        }
    }
}

```

**Comment by artembilan** [comment]
Has been fixed via https://github.com/spring-projects/spring-amqp/issues/914.

Is going to be released for the next Spring AMQP 2.1.6 and, therefore, for  Spring Boot 2.1.5

**Comment by vavrfam** [comment]
Okay. Thanks!!

**Comment by vavrfam** [comment]
@artembilan  @garyrussell  The code I posted above still does not work (no beans gets processed)  in `2.1.5` release. Could you please take a look?  Thanks!!
Same code executed with `2.1.3` Springboot works and prints out the bean class info.

**Comment by vavrfam** [comment]
@artembilan Can we please re-open this issue?
Please let me know if you want me to create a new issue.

**Comment by artembilan** [comment]
I don't see reason to reopen or create a new one yet.

Please, share with us the project which exhibits the problem.
Although I really would like to see there Spring AMQP 2.1.6, which has the fix for this issue.

Thanks for understanding.

**Comment by vavrfam** [comment]
Here it is
[demo.zip](https://github.com/spring-projects/spring-amqp/files/3228664/demo.zip)

**Comment by artembilan** [comment]
What is your goal? 
What you would like to achieve?

I have a couple concerns regarding your code:

1. Why do we need `spring.main.allow-bean-definition-overriding=true`? It is really an anti-pattern to do that. Something is wrong with your configuration...
2. What is the point to have an `@Import(RabbitAutoConfiguration.class)` if it is triggered by Spring Boot auto-configuration anyway? Isn't this something wrong from your configuration perspective?

When I remove it starts to work a bit further. 
We still fail because there is no `RabbitListenerConfigUtils.RABBIT_LISTENER_ENDPOINT_REGISTRY_BEAN_NAME` bean definition in the configuration. And that's because this bean can be available only when we pass the condition:
```
@Configuration
@EnableRabbit
@ConditionalOnMissingBean(
			name = RabbitListenerConfigUtils.RABBIT_LISTENER_ANNOTATION_PROCESSOR_BEAN_NAME)
protected static class EnableRabbitConfiguration {

}
```
Since you declare your own `CustomRabbitAnnotationListener`, that condition doesn't match and we don't have a `RabbitListenerConfigUtils.RABBIT_LISTENER_ENDPOINT_REGISTRY_BEAN_NAME` bean.
Therefore together with the `CustomRabbitAnnotationListener`, you need also declare a bean for the `RabbitListenerEndpointRegistry`:
```
    @Bean(name = RabbitListenerConfigUtils.RABBIT_LISTENER_ENDPOINT_REGISTRY_BEAN_NAME)
    public RabbitListenerEndpointRegistry rabbitListenerEndpointRegistry() {
        return new RabbitListenerEndpointRegistry();
    }
```

Also I have removed a `@Primary` from the `CustomRabbitAnnotationListener` as well, since there is not going to be more than one beans for this type and name.

So, the fix works and your project need adjustments to meet Spring Boot requirements.

Thanks for understanding!

**Comment by vavrfam** [comment]
@artembilan 
Thanks so much for the response. Your pointers helped.
In our framework, we override some of the configuration provided by the auto configuration.

**Comment by artembilan** [comment]
That's OK, it really a typical use-case in the enterprise, but it doesn't mean that you need to import auto-configuration classes manually.
And yes: sometime just a single bean is not enough to override...
